### ISSUE TITLE
Please add a (liberal, BSD or MIT, if possible) license

### ISSUE THREAD

**Issue by ccordoba12** [chrisconlan/md_math_to_pdf#1]
This looks really cool! Thanks for sharing!

I'm the Spyder maintainer and we could use your code in our authoring plugin called [spyder-reports](https://github.com/spyder-ide/spyder-reports). But for that we need you to please add a license to your repo, so we can use it legally.

Thanks!

**Comment by chrisconlan** [comment]
Added MIT License. I'm a big fan of Anaconda and Spyder. Honored to help.

**Comment by ccordoba12** [comment]
Thanks!
